LibraryApi done and up to par with FollowApi style
Ringobot/SpotifyApi.NetCore pull request #33
Opened 2020-06-30 16:08 UTC by akshays2112

LibraryApi is done and up to par with FollowApi style of coding and commenting.

2020-06-30 17:54 UTC, DanielLarsenNZ requested changes
This is awesome, thank you @akshays2112. Just a few naming changes to match Spotify docs (which are inconsistent I know, but I want to follow them). Also some unnecessary use of `async` `await` keywords - this is minor but we should stay consistent with other classes.

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +            ) => await CheckUserSavedAlbums<bool[]>(albumIds, accessToken);
* Method name should be `CheckUsersSavedAlbums`
* Don't `async` `await` here. No need to unwind the Task. This goes for all non-generic methods that are proxies for the Generic version 🙂

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +            ) => await CheckUserSavedShows<bool[]>(showIds, accessToken);
* Method name should be `CheckUsersSavedShows`
* Remove `async` and `await` keywords here.

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +            ) => await CheckUserSavedTracks<bool[]>(trackIds, accessToken);
* Method name = `CheckUsersSavedTracks`
* Remove `async` and `await` keywords here.

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +            ) => await GetUserSavedAlbums<PagedAlbums>(limit, offset, market, accessToken);
Remove `async` and `await` keywords here.

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task<T> CheckUserSavedAlbums<T>(
Method name should be `CheckUsersSavedAlbums`

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task<T> CheckUserSavedShows<T>(
Method name should be `CheckUsersSavedShows`

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task<T> CheckUserSavedTracks<T>(
Method name = `CheckUsersSavedTracks`

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task<PagedAlbums> GetUserSavedAlbums(
* Method name = `GetCurrentUsersSavedAlbums`
* Remove `async` `await` keywords

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        /// <param name="market">Optional. An ISO 3166-1 alpha-2 country code or the string from_token. Provide this parameter if you want to apply Track Relinking.</param>
Mention the `SpotifyCountryCodes` helper here e.g.

```csharp
/// <param name="market">Optional. An ISO 3166-1 alpha-2 country code or the string from_token <see cref="SpotifyCountryCodes" />. Provide this parameter if you want to apply Track Relinking.</param>
```

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task<T> GetUserSavedAlbums<T>(
Method name = `GetCurrentUsersSavedAlbums`

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        /// <param name="market">Optional. An ISO 3166-1 alpha-2 country code or the string from_token. Provide this parameter if you want to apply Track Relinking.</param>
Mention the `SpotifyCountryCodes` helper here e.g.

```csharp
/// <param name="market">Optional. An ISO 3166-1 alpha-2 country code or the string from_token <see cref="SpotifyCountryCodes" />. Provide this parameter if you want to apply Track Relinking.</param>
```

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task<PagedShows> GetUserSavedShows(
* Method name = `GetUsersSavedShows`
* Remove `async` and `await` keywords here

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task<T> GetUserSavedShows<T>(
Method name = `GetUsersSavedShows`

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task<PagedTracks> GetUserSavedTracks(
* Method name = `GetUsersSavedTracks`
* Remove `async` and `await` keywords here

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        /// <param name="market">Optional. An ISO 3166-1 alpha-2 country code or the string from_token. Provide this parameter if you want to apply Track Relinking.</param>
Mention the `SpotifyCountryCodes` helper here e.g.

```csharp
/// <param name="market">Optional. An ISO 3166-1 alpha-2 country code or the string from_token <see cref="SpotifyCountryCodes" />. Provide this parameter if you want to apply Track Relinking.</param>
```

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task<T> GetUserSavedTracks<T>(
* Method name = `GetUsersSavedTracks`

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        /// <param name="market">Optional. An ISO 3166-1 alpha-2 country code or the string from_token. Provide this parameter if you want to apply Track Relinking.</param>
Mention the `SpotifyCountryCodes` helper here e.g.

```csharp
/// <param name="market">Optional. An ISO 3166-1 alpha-2 country code or the string from_token <see cref="SpotifyCountryCodes" />. Provide this parameter if you want to apply Track Relinking.</param>
```

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task RemoveUserSavedShows(
Method name = `RemoveUsersSavedShows`

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        /// <param name="market">Optional. An ISO 3166-1 alpha-2 country code. If a country code is specified, only shows that are available in that market will be removed. If a valid user access tok
Mention the `SpotifyCountryCodes` helper here e.g.

```csharp
/// <param name="market">Optional. An ISO 3166-1 alpha-2 country code or the string from_token <see cref="SpotifyCountryCodes" />. Provide this parameter if you want to apply Track Relinking.</param>
```

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task RemoveUserSavedTracks(
Method name = `RemoveUsersSavedTracks`

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/LibraryApi.cs
> +        public async Task SaveTracksForCurrentUser(
Method name = `SaveTracksForUser`

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/ILibraryApi.cs
> +﻿using SpotifyApi.NetCore.Models;
See review comments on `LibraryApi.cs` for changes to this interface

2020-06-30 17:54 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore.Tests/LibraryApiTests.cs
> +        [TestCategory("Integration")]
Please add User test category to all tests as they require User auth, e.g.

```csharp
[TestCategory("Integration")]
[TestCategory("User")]
```

2020-06-30 18:08 UTC, akshays2112 commented
Hi Daniel,

I got it. I am on it right away as it will not take much time.  I am watching this brilliant interviewer and of course Ronald Regan who is giving very smart responses to his questions.

Thanks for your patience and time.

Best Regards,

Akshay Srinivasan

2020-06-30 19:05 UTC, akshays2112 commented
Hi Daniel,

Sorry took so long. I am beggining now via pattern recognition to understand why these naming conventions of mine are going wrong.  Also the problem that came out of my understanding is the Spotify API naming conventions are inconsistent.  If you are using CurrentUser for Albumns but only using User for Shows then I expect that there should be a different meaning when one time they say Current User and when they say User only. This is why I was getting it wrong.

Thanks for your patience and time.

Best Regards,

Akshay Srinivasan

2020-06-30 23:24 UTC, DanielLarsenNZ approved these changes
BOOM 💥

2020-06-30 23:24 UTC, merged

2020-06-30 23:24 UTC, akshays2112 commented
♥♥♥♥

2020-07-01 00:10 UTC, akshays2112 commented
Hi Daniel,

I could not figure out your logic of which test to mark as [TestCategory("User")].
First I thought by looking at your modifications to FollowApiTests that it is maybe only if the current user account is being modified i.e. the current user account is the target of the action.
Or maybe is it when the user account is being accessed either read or write in any form.
Please clarify this soon as you see this. I am awaiting your response and then can finish off everything and create pull request for EpisodesApi.

Thanks for your patience and time.

Best Regards,

Akshay Srinivasan