Added 2 new endpoints for PlaylistsApi.
Ringobot/SpotifyApi.NetCore pull request #41
Opened 2020-07-19 12:57 UTC by akshays2112

2020-07-25 11:18 UTC, akshays2112 commented
Hi Daniel,

Requesting just a quick look at the way I solved the Dynamic Object/Class Type problem with Newtonsoft.Json ShouldSerialize<PropName>() method.

This is WIP.  Please approve of this and then I continue and finish of all endpoints first pass.  Then consolidate using your classes and return types (classes) from the other pull request of yours and that should save you time I think.  Well other than review time.

Thanks for your patience and time.

Best Regards,

Akshay Srinivasan

2020-07-27 09:55 UTC, DanielLarsenNZ commented
Hi Akshay,

You don't need `ShouldSerialize` at all. You can replace this object with my example here: https://github.com/Ringobot/SpotifyApi.NetCore/pull/40/files#diff-0980c5ae9847c84bd559259bfae5ab7eR7

Notice the use of `NullValueHandling` attribute arguments here.

I have also changed `SpotifyWebApi` to return a new `SpotifyResponse` instead of `HttpResponse` from `Post` methods. I have added a new generic overload so that you can return a deserialized object from `Post<T>()`. I have updated your PlaylistApi implementation to use this new helper.

2020-07-27 09:57 UTC, DanielLarsenNZ commented
For the release notes:

This release changes the return types of `Post`()` and `Put()` from `HttpResponse` to `SpotifyResponse<T>`. No internal callers were using the return type so this is not a breaking change. A new generic `Post<T>()` internal helper has been added to deserialize POST response bodies to an object typed `T`

2020-07-27 10:06 UTC, DanielLarsenNZ requested changes

2020-07-27 10:06 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/Models/Playlist.cs
> +    public partial class PlaylistSnapshotID
Please create a separate class file for this and rename to `ModifyPlaylistResponse`. See this example: https://github.com/Ringobot/SpotifyApi.NetCore/pull/40/files#diff-3070e73922144bda6f13360673a6810cR5

2020-07-27 10:06 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/IPlaylistsApi.cs
> +            );
We don't need a generic method for this one, thanks.

2020-07-27 10:06 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/IPlaylistsApi.cs
> +            string description = null,
Please use a request DTO here, see https://github.com/Ringobot/SpotifyApi.NetCore/pull/40/files#diff-bccd16b25f81b67901713ae0c33510e0R152

2020-07-27 10:06 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/PlaylistsApi.cs
> +        public async Task<T> AddItemsToPlaylist<T>(
Generic method is not needed here. Should return `ModifyPlaylistResponse`

2020-07-27 10:06 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/PlaylistsApi.cs
> +        class PutDataPayloadPlaylistDetails
Please don't nest classed. Create a new class. See https://github.com/Ringobot/SpotifyApi.NetCore/pull/40/files#diff-0980c5ae9847c84bd559259bfae5ab7eR5

2020-07-27 10:06 UTC, DanielLarsenNZ commented on src/SpotifyApi.NetCore/PlaylistsApi.cs
> +            }
Don't do this. See https://github.com/Ringobot/SpotifyApi.NetCore/pull/40/files#diff-0980c5ae9847c84bd559259bfae5ab7eR7

2020-07-27 18:00 UTC, akshays2112 commented
Hi Daniel,

Super. ♥ all of it. Will do it. Drinking right now (11:30PM here in Inja) so will do it tomorrow when sober.

Thanks for your patience and time.

Best Regards,

Akshay Srinivasan

2020-08-03 09:33 UTC, DanielLarsenNZ reviewed
How's this Akshay?

2020-08-03 10:16 UTC, akshays2112 commented
Hi Daniel,

You are an awesome coder my friend.  Yes, basically that damn deserializing bug was due to it being Paged<T> and not a regular thing.  Rest of all the changes are awesome.  Yes, this time I read through each and every one.

I think we can merge it if you are ok with it.
Then you can merge in your other pull request as you deem fit as usual.
Then I can sync up my stuff and continue closing out the remaining few endpoints easily.

Thanks for your patience and time.

Best Regards,

Akshay Srinivasan

2020-08-03 10:21 UTC, akshays2112 commented
Hi Daniel,

 

Went through all your changes. 100% approved.  Please merge and close out all pull requests and then I will sync and continue soon as I get word from you.  Ya the life issues were well life problems not health problems LOL.  Meh!! Sh*t happens you know LOL!

 

Cheers,

 

Akshay Srinivasan

+91-9884967112

Mumbai, India

 

From: Daniel Larsen <notifications@github.com> 
Sent: Monday, August 3, 2020 3:03 PM
To: Ringobot/SpotifyApi.NetCore <SpotifyApi.NetCore@noreply.github.com>
Cc: Akshay Srinivasan <akshays2112@gmail.com>; Author <author@noreply.github.com>
Subject: Re: [Ringobot/SpotifyApi.NetCore] Added 2 new endpoints for PlaylistsApi. (#41)

 

@DanielLarsenNZ commented on this pull request.

How's this Akshay?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/Ringobot/SpotifyApi.NetCore/pull/41#pullrequestreview-459884648> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AIRJIGVHWJTYEV44AIF5MJ3R6Z76TANCNFSM4PBJ3QRQ> .  <https://github.com/notifications/beacon/AIRJIGSZP5YKJT7WNRYHUDLR6Z76TA5CNFSM4PBJ3QR2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGODNUUQ2A.gif>

2020-08-03 20:06 UTC, merged